// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.12.4
// source: optionhub.v1.proto

package v1

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// message request
type SetAttributeByIdIn struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id of the row in the db
	AttributeId   int64  `protobuf:"varint,1,opt,name=attribute_id,json=attributeId,proto3" json:"attribute_id,omitempty"`
	Value         string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	ParentId      int64  `protobuf:"varint,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAttributeByIdIn) Reset() {
	*x = SetAttributeByIdIn{}
	mi := &file_optionhub_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAttributeByIdIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAttributeByIdIn) ProtoMessage() {}

func (x *SetAttributeByIdIn) ProtoReflect() protoreflect.Message {
	mi := &file_optionhub_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAttributeByIdIn.ProtoReflect.Descriptor instead.
func (*SetAttributeByIdIn) Descriptor() ([]byte, []int) {
	return file_optionhub_v1_proto_rawDescGZIP(), []int{0}
}

func (x *SetAttributeByIdIn) GetAttributeId() int64 {
	if x != nil {
		return x.AttributeId
	}
	return 0
}

func (x *SetAttributeByIdIn) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SetAttributeByIdIn) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

var File_optionhub_v1_proto protoreflect.FileDescriptor

var file_optionhub_v1_proto_rawDesc = string([]byte{
	0x0a, 0x12, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x68, 0x75, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x6a, 0x0a, 0x12, 0x53, 0x65, 0x74, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74,
	0x65, 0x42, 0x79, 0x49, 0x64, 0x49, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x74, 0x74, 0x72, 0x69,
	0x62, 0x75, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x61,
	0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x32, 0x55, 0x0a,
	0x10, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x68, 0x75, 0x62, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x41, 0x0a, 0x10, 0x53, 0x65, 0x74, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74,
	0x65, 0x42, 0x79, 0x49, 0x44, 0x12, 0x13, 0x2e, 0x53, 0x65, 0x74, 0x41, 0x74, 0x74, 0x72, 0x69,
	0x62, 0x75, 0x74, 0x65, 0x42, 0x79, 0x49, 0x64, 0x49, 0x6e, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x22, 0x00, 0x42, 0x10, 0x5a, 0x0e, 0x2e, 0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x68, 0x75, 0x62, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_optionhub_v1_proto_rawDescOnce sync.Once
	file_optionhub_v1_proto_rawDescData []byte
)

func file_optionhub_v1_proto_rawDescGZIP() []byte {
	file_optionhub_v1_proto_rawDescOnce.Do(func() {
		file_optionhub_v1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_optionhub_v1_proto_rawDesc), len(file_optionhub_v1_proto_rawDesc)))
	})
	return file_optionhub_v1_proto_rawDescData
}

var file_optionhub_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_optionhub_v1_proto_goTypes = []any{
	(*SetAttributeByIdIn)(nil), // 0: SetAttributeByIdIn
	(*empty.Empty)(nil),        // 1: google.protobuf.Empty
}
var file_optionhub_v1_proto_depIdxs = []int32{
	0, // 0: OptionhubService.SetAttributeByID:input_type -> SetAttributeByIdIn
	1, // 1: OptionhubService.SetAttributeByID:output_type -> google.protobuf.Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_optionhub_v1_proto_init() }
func file_optionhub_v1_proto_init() {
	if File_optionhub_v1_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_optionhub_v1_proto_rawDesc), len(file_optionhub_v1_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_optionhub_v1_proto_goTypes,
		DependencyIndexes: file_optionhub_v1_proto_depIdxs,
		MessageInfos:      file_optionhub_v1_proto_msgTypes,
	}.Build()
	File_optionhub_v1_proto = out.File
	file_optionhub_v1_proto_goTypes = nil
	file_optionhub_v1_proto_depIdxs = nil
}
